package docs

// This file is generated by swag init. Edit at your own risk.

// Package docs provides the Swagger documentation for EntityDB API.
// Version 2.6.0
// Schemes: http https
// Host: localhost:8085
// BasePath: /api/v1